# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='context',
            new_name='content',
        ),
    ]
