# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161025_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
