# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(default='01090818735', max_length=30),
            preserve_default=False,
        ),
    ]
