# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20161025_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Album',
            new_name='album',
        ),
    ]
