# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20161026_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 27, 11, 54, 24, 1458, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='modifed_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 27, 11, 55, 28, 21168, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='modifed_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photodislike',
            name='modifed_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photolike',
            name='modifed_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
